spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/pag_backend_db?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true